"""add_lot_id_to_entry_records

Revision ID: 0a0dac8b1e0c
Revises: 342a699edb05
Create Date: 2026-09-30 05:47:05.964846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0dac8b1e0c'
down_revision: Union[str, Sequence[str], None] = '342a699edb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if "weekly_lot_metrics" not in tables:
        op.create_table(
            "weekly_lot_metrics",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("lot_id", sa.String(length=50), nullable=False),
            sa.Column("week_start", sa.DateTime(), nullable=False),
            sa.Column("week_end", sa.DateTime(), nullable=False),
            sa.Column("utilization_percentage", sa.Float(), nullable=False),
            sa.Column("peak_occupancy", sa.Integer(), nullable=False),
            sa.Column("vehicle_count", sa.Integer(), nullable=False),
            sa.Column("avg_dwell_time_minutes", sa.Float(), nullable=False),
            sa.Column("generated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("lot_id", "week_start", name="uq_weekly_lot_metric"),
        )
        inspector = sa.inspect(bind)

    indexes = {index["name"] for index in inspector.get_indexes("weekly_lot_metrics")}
    if "ix_weekly_lot_metrics_id" not in indexes:
        op.create_index(
            "ix_weekly_lot_metrics_id", "weekly_lot_metrics", ["id"], unique=False
        )
    if "ix_weekly_lot_metrics_lot_id" not in indexes:
        op.create_index(
            "ix_weekly_lot_metrics_lot_id",
            "weekly_lot_metrics",
            ["lot_id"],
            unique=False,
        )
    if "ix_weekly_lot_metrics_week_start" not in indexes:
        op.create_index(
            "ix_weekly_lot_metrics_week_start",
            "weekly_lot_metrics",
            ["week_start"],
            unique=False,
        )

    entry_columns = {column["name"] for column in inspector.get_columns("entry_records")}
    if "lot_id" not in entry_columns:
        op.add_column(
            "entry_records", sa.Column("lot_id", sa.String(length=50), nullable=True)
        )
    entry_indexes = {index["name"] for index in inspector.get_indexes("entry_records")}
    if "ix_entry_records_lot_id" not in entry_indexes:
        op.create_index(
            "ix_entry_records_lot_id", "entry_records", ["lot_id"], unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_records_lot_id'), table_name='entry_records')
    op.drop_column('entry_records', 'lot_id')
    op.drop_index(op.f('ix_weekly_lot_metrics_week_start'), table_name='weekly_lot_metrics')
    op.drop_index(op.f('ix_weekly_lot_metrics_lot_id'), table_name='weekly_lot_metrics')
    op.drop_index(op.f('ix_weekly_lot_metrics_id'), table_name='weekly_lot_metrics')
    op.drop_table('weekly_lot_metrics')
    # ### end Alembic commands ###
