"""add_user_preferences_table

Revision ID: 342a699edb05
Revises: 8f2c554e80b1
Create Date: 2026-09-24 00:41:24.891491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342a699edb05'
down_revision: Union[str, Sequence[str], None] = '8f2c554e80b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
                    sa.Column('line_user_id', sa.String(), nullable=False),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('line_user_id')
                    )
    op.create_index(op.f('ix_user_preferences_line_user_id'), 'user_preferences', ['line_user_id'], unique=False)
    op.drop_constraint(op.f('admin_alert_deliveries_anomaly_id_line_user_id_key'), 'admin_alert_deliveries',
                       type_='unique')
    op.create_index(op.f('ix_admin_alert_deliveries_id'), 'admin_alert_deliveries', ['id'], unique=False)
    op.create_unique_constraint('uq_admin_alert_delivery', 'admin_alert_deliveries', ['anomaly_id', 'line_user_id'])
    op.drop_constraint(op.f('admin_alert_subscriptions_line_user_id_key'), 'admin_alert_subscriptions', type_='unique')
    op.drop_index(op.f('ix_admin_alert_subscriptions_line_user_id'), table_name='admin_alert_subscriptions')
    op.create_index(op.f('ix_admin_alert_subscriptions_line_user_id'), 'admin_alert_subscriptions', ['line_user_id'],
                    unique=True)
    op.create_index(op.f('ix_admin_alert_subscriptions_id'), 'admin_alert_subscriptions', ['id'], unique=False)

    # ⚡ สร้าง ENUM ใน PostgreSQL ก่อนทำการ Alter Column
    authprovider_enum = postgresql.ENUM('local', 'google', name='authprovider')
    authprovider_enum.create(op.get_bind(), checkfirst=True)

    approvalstatus_enum = postgresql.ENUM('pending', 'approved', 'rejected', 'revoked', name='approvalstatus')
    approvalstatus_enum.create(op.get_bind(), checkfirst=True)

    # ⚡ เพิ่ม postgresql_using เพื่อบอกวิธีแปลงข้อมูล
    op.alter_column('admins', 'auth_provider',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Enum('local', 'google', name='authprovider'),
                    nullable=False,
                    postgresql_using='auth_provider::authprovider')

    op.alter_column('admins', 'approval_status',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.Enum('pending', 'approved', 'rejected', 'revoked', name='approvalstatus'),
                    nullable=False,
                    postgresql_using='approval_status::approvalstatus')

    op.alter_column('admins', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_admins_oauth_sub'), 'admins', ['oauth_sub'], unique=True)
    op.drop_constraint(op.f('device_health_device_id_key'), 'device_health', type_='unique')
    op.create_index(op.f('ix_device_health_device_id'), 'device_health', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_health_id'), 'device_health', ['id'], unique=False)
    op.create_index(op.f('ix_parking_event_logs_lot_id'), 'parking_event_logs', ['lot_id'], unique=False)
    op.drop_index(op.f('ix_system_anomalies_open'), table_name='system_anomalies',
                  postgresql_where='(resolved_at IS NULL)')
    op.create_index(op.f('ix_system_anomalies_id'), 'system_anomalies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_anomalies_id'), table_name='system_anomalies')
    op.create_index(op.f('ix_system_anomalies_open'), 'system_anomalies', ['anomaly_type', 'lot_id', 'spot_id', 'device_id'], unique=False, postgresql_where='(resolved_at IS NULL)')
    op.drop_index(op.f('ix_parking_event_logs_lot_id'), table_name='parking_event_logs')
    op.drop_index(op.f('ix_device_health_id'), table_name='device_health')
    op.drop_index(op.f('ix_device_health_device_id'), table_name='device_health')
    op.create_unique_constraint(op.f('device_health_device_id_key'), 'device_health', ['device_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_admins_oauth_sub'), table_name='admins')
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admins', 'approval_status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'revoked', name='approvalstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admins', 'auth_provider',
               existing_type=sa.Enum('local', 'google', name='authprovider'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_admin_alert_subscriptions_id'), table_name='admin_alert_subscriptions')
    op.drop_index(op.f('ix_admin_alert_subscriptions_line_user_id'), table_name='admin_alert_subscriptions')
    op.create_index(op.f('ix_admin_alert_subscriptions_line_user_id'), 'admin_alert_subscriptions', ['line_user_id'], unique=False)
    op.create_unique_constraint(op.f('admin_alert_subscriptions_line_user_id_key'), 'admin_alert_subscriptions', ['line_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_admin_alert_delivery', 'admin_alert_deliveries', type_='unique')
    op.drop_index(op.f('ix_admin_alert_deliveries_id'), table_name='admin_alert_deliveries')
    op.create_unique_constraint(op.f('admin_alert_deliveries_anomaly_id_line_user_id_key'), 'admin_alert_deliveries', ['anomaly_id', 'line_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_preferences_line_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')

    # ⚡ เคลียร์ ENUM ทิ้งในกรณีที่สั่ง downgrade
    op.execute("DROP TYPE IF EXISTS authprovider;")
    op.execute("DROP TYPE IF EXISTS approvalstatus;")
    # ### end Alembic commands ###