"""add event log

Revision ID: 8f2c554e80b1
Revises: 792bc5525f00
Create Date: 2026-04-16 17:59:27.056959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2c554e80b1'
down_revision: Union[str, Sequence[str], None] = '792bc5525f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.String(length=50), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_event_logs_id'), 'parking_event_logs', ['id'], unique=False)
    op.create_index(op.f('ix_parking_event_logs_spot_id'), 'parking_event_logs', ['spot_id'], unique=False)
    op.create_index(op.f('ix_parking_event_logs_timestamp'), 'parking_event_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_event_logs_timestamp'), table_name='parking_event_logs')
    op.drop_index(op.f('ix_parking_event_logs_spot_id'), table_name='parking_event_logs')
    op.drop_index(op.f('ix_parking_event_logs_id'), table_name='parking_event_logs')
    op.drop_table('parking_event_logs')
    # ### end Alembic commands ###
